//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy_MVC_CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblYetenek
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Bu alan boþ býrakýlamaz !")]
        public string Yetenek { get; set; }
        [Range(1, 100,ErrorMessage ="Girilen deðer 1-100 arasýnda olmalý.")]
        public Nullable<byte> Oran { get; set; }
    }
}
